### ISSUE TITLE
design improvement

### ISSUE THREAD

**Issue by hy-otaku** [high-otaku/web#1]
creating an issue to **document and address design improvement** thoughts and requests

**general**

- [ ] decide on a color scheme _( nush )_
  - [x] improve the code set up for a 3 color scheme _( tado-mi )_
- [x] add an option for switching between 
  - [x] light and dark modes ( +1 from Iren )
  - [x] list and grid view for `<CustomList />`, `<SeasonList />`, `<EpisodeList />`, `<SubmangaList />`, `<VolumeList />` and `<Volume />` _( tado-mi #8 )_
    - [x] **!** we still need to address `<CustomList />`, `<EpisodeList />` and `<SubmangaList />` components for this
    - [x] thumbnails #10 
- [x] create a `<Logo />` component _( tado-mi )_
- [ ] create a `<Carousel />` component | discuss _( nush, tado-mi )_
- [x] improve on the anime / manga cards | discuss _( nush, tado-mi #11 )_

**artwork** _( nush )_
- [ ] create the collage image
- [ ] ? create individual logos for anime and manga
- [ ] for the about page
- [ ] default covers

**navigation**
- [x] highlight the selected section _( tado-mi )_
- [ ] ~add sub-menu items | discuss _( nush, tado-mi )_~
- [x] move the search bar to navigation _( tado-mi )_

**main**
- [ ] decide on the content

**anime**
- [x] move the header to the navigation bar _( tado-mi )_
- [x] a `<Video />` component with overlay _( tado-mi #9 )_

**manga**
- [x] move the header to the navigation bar _( tado-mi )_

**about**
- [ ] add a `Contact us` form _(ian)_

**Comment by tado-mi** [comment]
**thoughts / question**

I - on searchbar

- what should happen if the user clicks "search" outside of `/anime` or `/manga` url?

II - on ribbon

- [ ]  the overflow / scrolling needs to be addressed

III - in general

- [x] ? collapse the `<Piccha />` component when in `/anime` or `/manga` url | discuss _( nush, tado-mi)_

**Comment by tado-mi** [comment]
**iren feedback**

* մենյուն դժվարընթեռնելի ա background image-ի ֆոնին
* կարելի ա background image֊ը փոխել՝ ամեն բաժնին համապատասխան
  * նեղացնել նաև `<About />`֊ի համար 
* ~ավելացնել անգլերեն / ճապոներեն / ռուսերեն անվանումներ նյութերի մարմնին~
  * ~վերնագրերը անել հայերեն | անգլերեն․ `եռիքսահոլիք | xxxholic`~
  * ~**note:** data-ն հնարավոր ա, փոխվի~
* ~թեգերի սիտեմ որոնման համար~
